import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b border-gray-200 bg-white/70 dark:bg-black/40 backdrop-blur">
          <div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4">
            <Link href="/recipes" className="text-lg font-semibold">
              Recipe Lab
            </Link>
            <nav className="text-sm text-gray-600 dark:text-gray-300">
              <Link
                href="/recipes"
                className="hover:text-blue-600 dark:hover:text-blue-400"
              >
                All recipes
              </Link>
            </nav>
          </div>
        </header>
        <div className="mx-auto max-w-5xl px-6">{children}</div>
      </body>
    </html>
  );
}
